/* РАЗРЯД ЧПУ 0.990 — academy, shared machine profile and production log */
(function(){
'use strict';
const device=document.querySelector('.device');if(device)device.dataset.app='chpu';
const PROFILE_KEY='razryad-machine-profile-v99',SHOP_KEY='razryad-shop-log-v99',LEARN_KEY='razryad-learning-v99';
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch(_){return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const ehtml=s=>String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

const COURSE=[
 ['saf','Безопасность и первый осмотр','До включения станка'],['mach','Устройство станка','Понять узлы и ограничения'],['panel','Панель и режимы','RESET, HANDLE, MDI, MEMORY'],['first','Первый пуск','19 контролируемых шагов'],
 ['draw','Чертёж и базы','Размеры, допуски, шероховатость'],['meas','Измерение','Микрометр, нутромер, корректор'],['cutt','Режущий инструмент','Пластина, державка, износ'],['tdec','ISO-обозначения','Расшифровка инструмента'],['mode','Режимы резания','Vc, S, F, ap'],
 ['coord','Координаты','X в диаметрах, Z и знаки'],['zero','Нули станка и детали','Machine zero, work zero'],['bind','Привязка инструмента','Geometry и Wear'],['struct','Структура программы','Кадр, слово, модальность'],['move','G00–G03','Перемещения и дуги'],['corr','G41/G42','Компенсация вершины'],['cycl','Циклы','G71, G70, G75, G76'],['prog','Примеры','Разбор готового кода'],['err','Ошибки','Предварительная диагностика'],['rank','Разряды','Маршрут 3–6'],['exam','Экзамен','Проверка понимания']
];
const RANKS=[
 {n:'С нуля',d:'Безопасно включить станок, найти органы управления, прочитать простой чертёж.',topics:['saf','mach','panel','first']},
 {n:'3-й разряд',d:'Работать по готовой программе, измерять, вводить Wear и менять твердосплавную пластину или напайной резец.',topics:['draw','meas','cutt','bind']},
 {n:'4-й разряд',d:'Подбирать режимы, корректировать программу и вести типовую наладку.',topics:['mode','coord','zero','struct']},
 {n:'5-й разряд',d:'Программировать циклы, расточку, резьбу и сложный профиль.',topics:['move','corr','cycl','prog']},
 {n:'6-й разряд',d:'Диагностировать процесс, оптимизировать и отвечать за первую деталь.',topics:['err','brak','alarm','exam']}
];

function progress(){const p=load(LEARN_KEY,{}),ids=new Set(FOLDERS_BASE.learn.map(x=>x[0]));let done=0;ids.forEach(id=>{if(p[id])done++});return{done,total:ids.size,p,pct:ids.size?Math.round(done/ids.size*100):0};}
function academyHome(){const s=progress();return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/learn.jpg')"><span class="kicker">Академия оператора · 0.99</span><h2>С нуля до самостоятельной наладки</h2><p>Маршрут связывает учебник, расчёты, рабочие инструменты и практическую проверку у станка.</p></div>
 <div class="card"><div class="v99-progress-row"><b>Пройдено тем</b><span>${s.done} из ${s.total} · ${s.pct}%</span></div><div class="v99-progress"><i style="width:${s.pct}%"></i></div><div class="v99-toast-note">Отметка хранится только на этом устройстве. Она показывает изучение материала, а не допуск к самостоятельной работе.</div></div>
 <div class="sec">Маршрут подготовки</div>${RANKS.map((r,i)=>{const d=r.topics.filter(x=>s.p[x]).length,pc=Math.round(d/r.topics.length*100);return `<div class="card" data-v99-route="learn:${r.topics[0]}"><div class="row"><div><div class="tag">Этап ${i+1}</div><div style="font:500 17px Oswald;margin-top:5px">${r.n}</div></div><b style="font:600 18px IBM Plex Mono;color:var(--ember)">${pc}%</b></div><div class="ct" style="font-size:12px;margin-top:7px">${r.d}</div><div class="v99-progress" style="margin-top:9px"><i style="width:${pc}%"></i></div></div>`}).join('')}
 <div class="v99-grid"><div class="v99-card learn" data-v99-route="learn:rank"><i>3–6</i><b>По разрядам</b><span>Навыки и практические задания</span></div><div class="v99-card codes" data-v99-route="learn:exam"><i>?</i><b>Экзамен</b><span>Вопросы с объяснением ошибок</span></div></div>
 <div class="sec">Как рождается первая деталь</div><div class="v99-diagram"><svg viewBox="0 0 360 154" role="img" aria-label="Маршрут от чертежа до первой детали"><defs><marker id="av99" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0 6 3 0 6" fill="#ff8c28"/></marker></defs><g fill="#151b20" stroke="#39434c"><rect x="12" y="26" width="88" height="42" rx="8"/><rect x="136" y="26" width="88" height="42" rx="8"/><rect x="260" y="26" width="88" height="42" rx="8"/><rect x="74" y="98" width="88" height="42" rx="8"/><rect x="198" y="98" width="88" height="42" rx="8"/></g><g text-anchor="middle"><text x="56" y="44">ЧЕРТЁЖ</text><text x="56" y="57">И БАЗЫ</text><text x="180" y="44">ПРОГРАММА</text><text x="180" y="57">И КОРРЕКТОРЫ</text><text x="304" y="44">GRAPHICS</text><text x="304" y="57">SINGLE BLOCK</text><text x="118" y="116">ИЗМЕРЕНИЕ</text><text x="118" y="129">ПЕРВОЙ ДЕТАЛИ</text><text x="242" y="116">WEAR</text><text x="242" y="129">И ПОВТОР</text></g><g stroke="#ff8c28" stroke-width="2" marker-end="url(#av99)"><path d="M102 47h30"/><path d="M226 47h30"/><path d="M304 72c0 27-14 47-15 47"/><path d="M194 119h-28"/></g></svg></div>
 <div class="v99-source"><b>Проверяемая основа:</b> руководство конкретной стойки имеет приоритет. <a href="https://www.haascnc.com/owners/Service/operators-manual.html" target="_blank" rel="noopener">Официальные руководства Haas</a>; режимы инструмента сверяйте с паспортом производителя пластины.</div></div>`;}

function rankMatrix(){return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/learn.jpg')"><span class="kicker">Квалификационный маршрут</span><h2>Разряд — это наблюдаемый навык</h2><p>Каждый уровень заканчивается практическим действием под контролем наставника, а не только чтением текста.</p></div>${RANKS.slice(1).map((r,i)=>`<div class="card"><div class="row"><div class="tag">${r.n}</div><span class="v99-source-badge">практика</span></div><div class="ct" style="margin-top:8px">${r.d}</div><div style="margin-top:9px">${r.topics.map(t=>{const q=COURSE.find(x=>x[0]===t);return `<button class="v99-pill" style="margin:0 5px 5px 0" data-v99-route="learn:${t}">${q?q[1]:t}</button>`}).join('')}</div></div>`).join('')}</div>`;}

const coreViewEdu=viewEdu;viewEdu=function(){return academyHome()+coreViewEdu();};
const coreLearnContent=learnContent;learnContent=function(f){let h=coreLearnContent(f);if(f==='rank'&&!rank)h=rankMatrix()+h;const p=progress().p,done=!!p[f];return h+`<div class="wrap"><div class="card"><label class="v99-check" style="margin:0"><input type="checkbox" data-v99-complete="${ehtml(f)}" ${done?'checked':''}><span><b>Тема изучена и отработана</b><span>Отмечайте только после чтения, ответа на контрольные вопросы и практики с наставником.</span></span></label></div></div>`;};

function profileDefault(){return{machine:'st20',name:'Haas ST-20',maxRpm:4000,turret:'rear',xMode:'diameter',safeX:100,safeZ:20,chuckD:210,jawGrip:25,jawZ:-120,tools:'T0101 · CNMG R0.8 · наружный\nT0202 · CCMT R0.4 · расточной'};}
function profileValidate(p){const issues=[];if(!(p.maxRpm>0&&p.maxRpm<=20000))issues.push('лимит оборотов');if(!(p.safeX>0))issues.push('безопасный X');if(!(p.safeZ>=0))issues.push('безопасный Z');if(!(p.chuckD>0))issues.push('диаметр патрона');if(!(p.jawGrip>0))issues.push('длина зажима');return issues;}
function viewProfile(){const p={...profileDefault(),...load(PROFILE_KEY,{})};return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/work.jpg')"><span class="kicker">Общий профиль</span><h2>Станок, патрон и револьвер</h2><p>Эти значения использует мастер G-кода и рабочие проверки. Сверьте их с паспортом своего станка.</p></div><div class="card"><label class="fld"><span>Профиль станка</span><select id="mpMachine"><option value="st10" ${p.machine==='st10'?'selected':''}>Haas ST-10</option><option value="st20" ${p.machine==='st20'?'selected':''}>Haas ST-20</option><option value="st30" ${p.machine==='st30'?'selected':''}>Haas ST-30</option><option value="tl1" ${p.machine==='tl1'?'selected':''}>Haas TL-1</option><option value="custom" ${p.machine==='custom'?'selected':''}>Другой</option></select></label><label class="fld"><span>Название</span><input id="mpName" value="${ehtml(p.name)}"></label><div class="two"><label class="fld"><span>Максимум шпинделя</span><input type="number" id="mpMax" value="${p.maxRpm}"></label><label class="fld"><span>Револьвер</span><select id="mpTurret"><option value="rear" ${p.turret==='rear'?'selected':''}>Задняя</option><option value="front" ${p.turret==='front'?'selected':''}>Передняя</option></select></label></div><div class="two"><label class="fld"><span>Ось X</span><select id="mpX"><option value="diameter" ${p.xMode==='diameter'?'selected':''}>В диаметрах</option><option value="radius" ${p.xMode==='radius'?'selected':''}>В радиусах</option></select></label><label class="fld"><span>Патрон Ø, мм</span><input type="number" id="mpChuck" value="${p.chuckD}"></label></div><div class="two"><label class="fld"><span>Безопасный X</span><input type="number" id="mpSafeX" value="${p.safeX}"></label><label class="fld"><span>Безопасный Z</span><input type="number" id="mpSafeZ" value="${p.safeZ}"></label></div><div class="two"><label class="fld"><span>Длина зажима, мм</span><input type="number" id="mpGrip" value="${p.jawGrip}"></label><label class="fld"><span>Торец кулачков Z</span><input type="number" id="mpJawZ" value="${p.jawZ}"></label></div><label class="fld"><span>Карта револьверной головки</span><textarea id="mpTools">${ehtml(p.tools)}</textarea></label><div id="mpResult"></div><button class="btn" id="mpSave">Сохранить профиль</button></div><div class="v99-status warn"><b>Компенсация G41/G42 не выбирается только по слову «передняя/задняя».</b><span>Перед первой программой проверьте ориентацию вершины, направление прохода и поле Tip Direction в OFFSET конкретного станка.</span></div></div>`;}

function shopDefault(){return{program:'O0100',part:'',edge:1,good:0,reject:0,target:20,note:'',events:[]};}
function shopStats(s){const total=(+s.good||0)+(+s.reject||0),rejectRate=total?Math.round(s.reject/total*1000)/10:0,edgeLeft=Math.max(0,(+s.target||0)-(+s.good||0));return{total,rejectRate,edgeLeft};}
function viewShop(){const s={...shopDefault(),...load(SHOP_KEY,{})},k=shopStats(s);return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/control.jpg')"><span class="kicker">Ресурс твердосплавной пластины</span><h2>Журнал инструмента</h2><p>Годные детали, брак, рабочая позиция сменной пластины и причина её поворота или замены.</p></div><div class="card"><div class="two"><label class="fld"><span>Программа</span><input id="slProgram" value="${ehtml(s.program)}"></label><label class="fld"><span>Деталь</span><input id="slPart" value="${ehtml(s.part)}" placeholder="Вал 02.015"></label></div><div class="two"><label class="fld"><span>Позиция пластины №</span><input type="number" id="slEdge" value="${s.edge}" min="1"></label><label class="fld"><span>План деталей на позицию</span><input type="number" id="slTarget" value="${s.target}" min="1"></label></div><div class="v99-kpis"><div class="v99-kpi"><span>Годных</span><b id="slGood">${s.good}</b></div><div class="v99-kpi"><span>Брак</span><b id="slReject">${s.reject}</b></div><div class="v99-kpi"><span>Осталось по плану</span><b id="slLeft">${k.edgeLeft}</b></div><div class="v99-kpi"><span>Доля брака</span><b id="slRate">${k.rejectRate}%</b></div></div><label class="fld" style="margin-top:11px"><span>Наблюдение</span><textarea id="slNote" placeholder="Стружка, звук, износ, коррекция…">${ehtml(s.note)}</textarea></label><div class="v99-actions three"><button class="v99-mini primary" data-shop="good">+ Годная</button><button class="v99-mini" data-shop="reject">+ Брак</button><button class="v99-mini" data-shop="edge">Повернуть / заменить пластину</button></div></div><div class="card"><div class="row"><div class="tag">Последние события</div><button class="v99-mini" id="slExport">Экспорт</button></div><div id="slEvents" style="margin-top:8px">${shopEvents(s)}</div></div></div>`;}
function shopEvents(s){return(s.events||[]).slice(0,20).map(x=>`<div style="padding:8px 0;border-bottom:1px solid #24272c"><div class="row"><b style="font:500 11px IBM Plex Mono">${ehtml(x.type)}</b><span class="hint" style="margin:0">${ehtml(x.ts)}</span></div>${x.note?`<div class="ct" style="font-size:11px;margin-top:3px">${ehtml(x.note)}</div>`:''}</div>`).join('')||'<div class="hint">Событий пока нет.</div>';}

function custom(title,sub,html,section){$('#ttl').textContent=title;$('#sub').textContent=sub;$('#searchbox').style.display='none';$('#chips').style.display='none';$('#mseg').style.display='none';drawNav();$('#screen').innerHTML=html;if(device)device.dataset.section=section;bind();numFix();$('#screen').classList.remove('v99-enter');void $('#screen').offsetWidth;$('#screen').classList.add('v99-enter');$('#screen').scrollTop=0;}
const coreRender=render;render=function(){if(tab==='work'&&folder==='profilex')return custom('Профиль станка','Общие ограничения для расчётов и G-кода',viewProfile(),'work');coreRender();if(device)device.dataset.app='chpu';if(tab==='work'&&!folder)enhanceWork();$('#screen').classList.remove('v99-enter');void $('#screen').offsetWidth;$('#screen').classList.add('v99-enter');};

function enhanceWork(){if(window.RazryadTools&&typeof window.RazryadTools.workCatalog==='function')return;const grid=document.querySelector('.work-grid');if(!grid||grid.querySelector('[data-work-v99]'))return;grid.insertAdjacentHTML('beforeend',`<div class="work-card work" data-work-v99="profilex"><i style="font:600 20px IBM Plex Mono;color:var(--ember);font-style:normal">P</i><b>Профиль станка</b><span>Патрон, лимиты и карта инструментов</span></div>`);document.querySelectorAll('[data-work-v99]').forEach(x=>x.onclick=()=>{folder=x.dataset.workV99;deeper();render();});}

const coreBind=bind;bind=function(){coreBind();bindV99();};
function bindV99(){
 document.querySelectorAll('[data-v99-route]').forEach(x=>x.onclick=()=>{const [t,f]=x.dataset.v99Route.split(':');tab=t;folder=f||null;rank=null;filter='Все';deeper();render();});
 document.querySelectorAll('[data-v99-complete]').forEach(x=>x.onchange=()=>{const p=load(LEARN_KEY,{});p[x.dataset.v99Complete]=x.checked;save(LEARN_KEY,p);toast(x.checked?'Тема отмечена':'Отметка снята');});
 const ms=$('#mpSave');if(ms)ms.onclick=()=>{const p={machine:$('#mpMachine').value,name:$('#mpName').value.trim(),maxRpm:+$('#mpMax').value,turret:$('#mpTurret').value,xMode:$('#mpX').value,safeX:+$('#mpSafeX').value,safeZ:+$('#mpSafeZ').value,chuckD:+$('#mpChuck').value,jawGrip:+$('#mpGrip').value,jawZ:+$('#mpJawZ').value,tools:$('#mpTools').value.trim()},issues=profileValidate(p);$('#mpResult').innerHTML=issues.length?`<div class="v99-status bad"><b>Проверьте: ${issues.join(', ')}</b></div>`:`<div class="v99-status"><b>Профиль проверен и сохранён</b><span>Мастер G-кода подхватит его при следующем открытии.</span></div>`;if(!issues.length){save(PROFILE_KEY,p);toast('Профиль станка сохранён');}};
 const machine=$('#mpMachine');if(machine)machine.onchange=()=>{const m={st10:['Haas ST-10',6000,165],st20:['Haas ST-20',4000,210],st30:['Haas ST-30',3400,254],tl1:['Haas TL-1',1800,203]}[machine.value];if(m){$('#mpName').value=m[0];$('#mpMax').value=m[1];$('#mpChuck').value=m[2];}};
 document.querySelectorAll('[data-shop]').forEach(b=>b.onclick=()=>shopAction(b.dataset.shop));
 const ex=$('#slExport');if(ex)ex.onclick=()=>{const s=load(SHOP_KEY,shopDefault()),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));a.download='razryad-smena-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);};
 addVoiceButton();
 addSetupPhoto();
}
function readShop(){const old={...shopDefault(),...load(SHOP_KEY,{})};return{...old,program:$('#slProgram')?$('#slProgram').value.trim():old.program,part:$('#slPart')?$('#slPart').value.trim():old.part,edge:$('#slEdge')?+$('#slEdge').value:old.edge,target:$('#slTarget')?+$('#slTarget').value:old.target,note:$('#slNote')?$('#slNote').value.trim():old.note};}
function shopAction(kind){const s=readShop(),ts=new Date().toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});if(kind==='good'){s.good++;s.events.unshift({type:'Годная деталь',ts,note:s.note});}if(kind==='reject'){s.reject++;s.events.unshift({type:'Брак',ts,note:s.note||'Причина не указана'});}if(kind==='edge'){s.edge++;s.good=0;s.events.unshift({type:'Новая позиция пластины '+s.edge,ts,note:s.note});}s.note='';save(SHOP_KEY,s);render();}
function addVoiceButton(){const note=document.querySelector('[data-setup="note"]');if(!note||document.querySelector('#v99Voice'))return;const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return;const b=document.createElement('button');b.id='v99Voice';b.className='v99-mini';b.type='button';b.textContent='🎙 Диктовка заметки';note.parentElement.appendChild(b);b.onclick=()=>{
 /* Web Speech API в Chrome и Android WebView распознаёт не на устройстве: звук
    уходит на серверы Google. Приложение объявляет себя офлайновым, поэтому
    единственная функция, которая это нарушает, должна спрашивать явно. */
 if(!sessionStorage.getItem('razryad-voice-ok')){
  if(!confirm('Диктовка работает не на устройстве: браузер отправит записанный звук на серверы Google для распознавания. Остальные функции приложения работают офлайн.\n\nВключить диктовку?'))return;
  try{sessionStorage.setItem('razryad-voice-ok','1')}catch(_){}
 }
 const r=new R();r.lang='ru-RU';r.interimResults=false;b.textContent='Слушаю…';r.onresult=e=>{note.value=(note.value+' '+e.results[0][0].transcript).trim();note.dispatchEvent(new Event('input',{bubbles:true}));};r.onend=()=>b.textContent='🎙 Диктовка заметки';r.onerror=()=>{b.textContent='🎙 Диктовка заметки';toast('Диктовка недоступна');};r.start();};}
function addSetupPhoto(){if(folder!=='setupx'||document.querySelector('#v99SetupPhoto'))return;const checks=document.querySelector('.checklist');if(!checks)return;const card=checks.closest?checks.closest('.card'):checks.parentElement,src=localStorage.getItem('razryad-setup-photo-v99')||'';card.insertAdjacentHTML('beforebegin',`<div class="card" id="v99SetupPhoto"><div class="tag">Фотография наладки</div>${src?`<img src="${src}" alt="Фотография текущей наладки" style="width:100%;max-height:230px;object-fit:cover;border-radius:11px;margin-top:9px">`:''}<div class="v99-actions" style="margin-top:9px"><button class="v99-mini primary" id="v99SetupPhotoAdd">${src?'Заменить':'Сфотографировать'}</button><button class="v99-mini" id="v99SetupPhotoDel" ${src?'':'disabled'}>Удалить</button></div><input type="file" id="v99SetupPhotoFile" accept="image/*" capture="environment" hidden><div class="v99-toast-note">Снимок хранится только на этом устройстве. Сфотографируйте кулачки, вылет и положение сопла без людей и персональных данных.</div></div>`);$('#v99SetupPhotoAdd').onclick=()=>$('#v99SetupPhotoFile').click();$('#v99SetupPhotoDel').onclick=()=>{localStorage.removeItem('razryad-setup-photo-v99');render();};$('#v99SetupPhotoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const img=new Image();img.onload=()=>{const scale=Math.min(1,900/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);try{localStorage.setItem('razryad-setup-photo-v99',c.toDataURL('image/jpeg',.72));toast('Фотография наладки сохранена');render();}catch(_){toast('Фото слишком большое для памяти устройства');}URL.revokeObjectURL(img.src);};img.src=URL.createObjectURL(f);};}

window.RazryadV99={progress,profileValidate,shopStats,profileDefault};
render();
})();
