/* РАЗРЯД Фото → G-код 0.990 — contour editor, shared machine profile, safety audit */
(function(){
'use strict';
const KEY='razryad-machine-profile-v99';
const MACH={st10:{name:'Haas ST-10',maxRpm:6000,chuckD:165},st20:{name:'Haas ST-20',maxRpm:4000,chuckD:210},st30:{name:'Haas ST-30',maxRpm:3400,chuckD:254},tl1:{name:'Haas TL-1',maxRpm:1800,chuckD:203},custom:{name:'Другой станок',maxRpm:2500,chuckD:200}};
const loadProfile=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){return null}};
const saveProfile=p=>{try{localStorage.setItem(KEY,JSON.stringify(p))}catch(_){}};
function defaults(){return{machine:'st20',name:'Haas ST-20',maxRpm:4000,turret:'rear',xMode:'diameter',safeX:100,safeZ:20,chuckD:210,jawGrip:25,jawZ:-120,tools:'',extComp:'G42',idComp:'G41'};}
function currentProfile(){return{...defaults(),...(loadProfile()||{})};}
function applyProfile(){const p=currentProfile(),m=MACH[p.machine]||MACH.custom;state.machineKey=p.machine;state.machine={...(state.machine||{}),name:p.name||m.name,maxRpm:+p.maxRpm||m.maxRpm,chuck:+p.chuckD||m.chuckD};state.maxRpm=Math.min(+state.maxRpm||m.maxRpm,+p.maxRpm||m.maxRpm);state.chuckD=+p.chuckD||m.chuckD;state.jawGrip=+p.jawGrip||25;state.sharedProfile=p;state.extComp=p.extComp||'G42';state.idComp=p.idComp||'G41';}
applyProfile();

function profileCard(){const p=currentProfile();return `<div class="card" id="v99MachineCard"><div class="flabel"><span>Общий профиль приложения</span><span class="tag green">0.99</span></div><div class="material-summary" style="margin-top:9px"><span class="matdot">P</span><div><b>${esc(p.name)}</b><span>${p.maxRpm} об/мин · патрон Ø${p.chuckD} · ${p.turret==='front'?'передняя':'задняя'} револьверная</span><span style="color:var(--ember);margin-top:3px">X ${p.xMode==='diameter'?'в диаметрах':'в радиусах'} · безопасно X${p.safeX} Z${p.safeZ}</span></div></div><div class="two" style="margin-top:11px"><label class="fld"><span>Наружная компенсация</span><select id="v99ExtComp"><option value="G42" ${state.extComp==='G42'?'selected':''}>G42</option><option value="G41" ${state.extComp==='G41'?'selected':''}>G41</option></select></label><label class="fld"><span>Внутренняя компенсация</span><select id="v99IdComp"><option value="G41" ${state.idComp==='G41'?'selected':''}>G41</option><option value="G42" ${state.idComp==='G42'?'selected':''}>G42</option></select></label></div><div class="compact-note">Выбор компенсации должен соответствовать направлению прохода и номеру вершины в OFFSET. Профиль можно изменить в ЧПУ → Работа → Профиль станка.</div></div>`;}

const baseMaterials=renderMaterials;renderMaterials=function(){applyProfile();baseMaterials();const host=$('#proSetup');if(host&&!$('#v99MachineCard'))host.insertAdjacentHTML('afterbegin',profileCard());const ex=$('#v99ExtComp'),inn=$('#v99IdComp');if(ex)ex.onchange=e=>{state.extComp=e.target.value;persistComp();};if(inn)inn.onchange=e=>{state.idComp=e.target.value;persistComp();};const rpm=$('#maxRpm');if(rpm)rpm.value=Math.min(+rpm.value||state.maxRpm,currentProfile().maxRpm);};
function persistComp(){const p=currentProfile();p.extComp=state.extComp;p.idComp=state.idComp;saveProfile(p);}

function contourTools(){const maps=(state.ocrFeatures||[]).map((f,i)=>`<div class="v99-ocr-row"><b>${esc(f.raw||f.type+' '+f.value)}</b><select data-v99-map="${i}"><option value="">Назначить переходу…</option>${state.features.map((_,j)=>`<option value="${j}">Переход ${j+1} → ${j+2}</option>`).join('')}</select></div>`).join('');return `<div id="v99ContourTools"><div class="card"><div class="flabel"><span>Редактор ступеней</span><span>${state.segments.length} участ.</span></div><div style="margin-top:9px">${state.segments.map((s,i)=>`<div class="v99-segtools"><b>${i+1}. Ø${num(s.d)} × ${s.l==null?'—':num(s.l)}</b><button data-v99-seg="up:${i}" title="Выше">↑</button><button data-v99-seg="down:${i}" title="Ниже">↓</button><button data-v99-seg="del:${i}" title="Удалить">×</button></div>`).join('')}</div><button class="swap" id="v99AddSegment" type="button">+ Добавить ступень</button><div class="compact-note">После перестановки переходы сбрасываются в «без фаски/радиуса», чтобы галтель или фаска не оказалась на другом уступе.</div></div>${maps?`<div class="card feature-card"><div class="eyebrow">Привязка выносок OCR</div><div class="v99-ocr-map" style="margin-top:8px">${maps}</div><div class="compact-note" style="margin-top:8px">Размер с фото назначается только после выбора оператора.</div></div>`:''}</div>`;}
const baseDimensions=renderDimensions;renderDimensions=function(){baseDimensions();const form=$('#dimensionForm');if(!form)return;const old=$('#v99ContourTools');if(old)old.remove();form.insertAdjacentHTML('afterend',contourTools());$('#v99AddSegment').onclick=()=>{if(state.segments.length>=12){toast('Не больше 12 участков в одном контуре');return;}const last=state.segments[state.segments.length-1]||{d:20,l:20};state.segments.push({d:Math.max(1,+last.d+5),l:Math.max(1,+last.l)});dirtyDims();renderDimensions();};document.querySelectorAll('[data-v99-seg]').forEach(b=>b.onclick=()=>editSegment(b.dataset.v99Seg));document.querySelectorAll('[data-v99-map]').forEach(s=>s.onchange=()=>{if(s.value==='')return;const f=state.ocrFeatures[+s.dataset.v99Map];state.features[+s.value]={type:f.type,value:+f.value||0,axial:+f.axial||+f.value||1};dirtyDims();renderDimensions();toast('Выноска назначена переходу');});};
function editSegment(cmd){const [act,raw]=cmd.split(':'),i=+raw;if(act==='del'){if(state.segments.length<=1){toast('Нужен минимум один участок');return;}state.segments.splice(i,1);}else{const j=act==='up'?i-1:i+1;if(j<0||j>=state.segments.length)return;[state.segments[i],state.segments[j]]=[state.segments[j],state.segments[i]];}state.features=[];dirtyDims();renderDimensions();}

const baseGenerate=generateGcode;generateGcode=function(){readSetup();let code=baseGenerate();code=code.replace(/RAZRYAD FOTO-GCODE V0980|RAZRYAD FOTO-GCODE/g,'RAZRYAD FOTO-GCODE V0990');code=code.replace(/N100 G00 G4[12]/,`N100 G00 ${state.extComp||'G42'}`).replace(/N200 G4[12] G00/,`N200 ${state.idComp||'G41'} G00`);const p=currentProfile();code=code.replace('(PROVERIT GRAPHICS SINGLE BLOCK RAPID 5%)',`(PROVERIT GRAPHICS SINGLE BLOCK RAPID 5%)\n(PROFILE ${ncText(p.name)} / X ${p.xMode.toUpperCase()} / TURRET ${p.turret.toUpperCase()})`);return code;};

function auditProgram(code){const issues=[],warn=[],p=currentProfile(),lines=String(code||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(p.xMode!=='diameter')issues.push('генератор выдаёт X в диаметрах, а профиль станка установлен «в радиусах»');if((+state.maxRpm||0)>(+p.maxRpm||0))issues.push(`G50 выше профиля станка ${p.maxRpm} об/мин`);const g96=lines.findIndex(x=>/\bG96\b/.test(x)),g50=lines.findIndex(x=>/\bG50\b/.test(x));if(g96>=0&&(g50<0||g50>g96))issues.push('G96 включён без предыдущего ограничения G50');if(/\bG4[12]\b/.test(code)&&!/\bG40\b/.test(code))issues.push('компенсация включена без отмены G40');if(/\bG83\b/.test(code)&&!/\bG80\b/.test(code))issues.push('цикл G83 не отменён G80');if(!/\bM0[34]\b/.test(code))issues.push('нет запуска шпинделя M03/M04');if(!/\bM30\b/.test(code))issues.push('нет завершения M30');if(p.turret==='front')warn.push('передняя револьверная: направление дуг и G41/G42 требуется проверить отдельно');if((+p.safeZ||0)<2)warn.push('безопасный Z профиля меньше 2 мм');if((+p.jawGrip||0)<Math.max(8,(+state.stockD||0)*.1))warn.push('малый зажим относительно диаметра заготовки');return{issues,warn};}
const baseSafety=checkSafety;checkSafety=function(){baseSafety();const a=auditProgram(state.gcode||generateGcode());if(a.issues.length){state.safe=false;$('#safetyStatus').className='status bad';$('#safetyTitle').textContent='Экспорт заблокирован проверкой 0.99';$('#safetyText').textContent=a.issues.join(' · ')+(a.warn.length?' · '+a.warn.join(' · '):'');$('#safetyCard').className='card warn';}else if(a.warn.length){$('#safetyTitle').textContent='Проверки пройдены · нужна ручная сверка';$('#safetyText').textContent+=($('#safetyText').textContent?' · ':'')+a.warn.join(' · ');}return a;};

function estimatePasses(){const d=Math.max(.1,+state.depth||1),outer=hasOuter()?Math.max(1,Math.ceil(Math.max(0,(+state.stockD||maxD())-minD())/2/d)):0,bore=hasBore()?Math.max(1,Math.ceil(Math.max(0,state.bore.finalD-state.bore.preD)/2/(d*.65))):0;return Math.max(1,outer+bore+(state.thread&&state.thread.enabled?1:0)+Object.values(state.extraOps||{}).filter(x=>x.enabled).length);}
const baseDraw=drawSim;drawSim=function(t=1){baseDraw(t);const c=$('#sim'),ctx=c.getContext('2d'),pts=contourPoints(),n=estimatePasses(),pass=Math.min(n,Math.max(1,Math.ceil(t*n))),idx=Math.min(pts.length-1,Math.max(0,Math.ceil(t*pts.length)-1)),p=pts[idx]||{x:0,z:0};ctx.save();ctx.fillStyle='rgba(8,12,16,.88)';ctx.fillRect(12,12,245,54);ctx.fillStyle='#ffa23a';ctx.font='600 17px Consolas';ctx.fillText(`ПРОХОД ${pass} / ${n}`,24,34);ctx.fillStyle='#b9c2ca';ctx.font='14px Consolas';ctx.fillText(`X${num(p.x,2)}  Z${num(p.z,2)}  ${Math.round(t*100)}%`,24,55);ctx.restore();const s=$('#v99SimRange');if(s&&!s.matches(':active'))s.value=Math.round(t*100);const l=$('#v99SimLabel');if(l)l.textContent=`${pass}/${n}`;};
function installSimControls(){const head=document.querySelector('.canvashead');if(!head||$('#v99StepSim'))return;const play=$('#playBtn');play.insertAdjacentHTML('beforebegin','<button class="btn secondary mini" id="v99StepSim">Шаг</button><button class="btn secondary mini" id="v99PauseSim">Пауза</button>');const wrap=document.querySelector('.canvaswrap');wrap.insertAdjacentHTML('beforeend','<div style="padding:8px 11px;border-top:1px solid var(--line)"><div class="flabel"><span>Проигрывание траектории</span><span id="v99SimLabel">1/'+estimatePasses()+'</span></div><input class="range" id="v99SimRange" type="range" min="0" max="100" value="100"></div>');let t=1;$('#v99StepSim').onclick=()=>{t=t>=1?0:Math.min(1,t+.08);drawSim(t);};$('#v99PauseSim').onclick=()=>{try{cancelAnimationFrame(anim)}catch(_){};toast('Анимация остановлена');};$('#v99SimRange').oninput=e=>{t=+e.target.value/100;drawSim(t);};}
installSimControls();

const baseGo=go;go=function(n){baseGo(n);if(n===4)setTimeout(()=>{applyProfile();const r=$('#maxRpm');if(r)r.value=Math.min(+r.value||state.maxRpm,currentProfile().maxRpm);},0);if(n===6)setTimeout(installSimControls,0);};

window.RazryadGeneratorV99={auditProgram,estimatePasses,currentProfile};
})();
