/* РАЗРЯД Термист 0.990 — work center, academy, process tools and verified-source layer */
(function(){
'use strict';
const dev=document.querySelector('.device');if(dev){dev.dataset.app='termist';dev.dataset.section='work';}
const STORE='razryad-thermist-v99',LEARN='razryad-thermist-learning-v99';
const tload=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch(_){return f}};
const tsave=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const tx=s=>String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let timerId=null,timerLeft=0,timerRunning=false;

const WORK=[
 {id:'cyclex',n:'Карта цикла',d:'Нагрев, выдержка, охлаждение и контроль',icon:'°',bg:'tp'},
 {id:'hardx',n:'Перевод твёрдости',d:'HRC, HB и HV — только ориентировочно',icon:'H',bg:'ts'},
 {id:'timerx',n:'Таймер выдержки',d:'Крупный экран, пауза и сигнал',icon:'T',bg:'tp'},
 {id:'batchx',n:'Журнал садок',d:'Режим, фактическая твёрдость и результат',icon:'#',bg:'tw'},
 {id:'defx',n:'Диагностика брака',d:'Признак → вероятная причина → проверка',icon:'!',bg:'ts'},
 {id:'furnacex',n:'Перед запуском',d:'Печь, среда, оснастка и безопасность',icon:'✓',bg:'tw'}
];

TABS.splice(0,TABS.length,
 {id:'work',n:'Работа',t:'Работа термиста',s:'Цикл, контроль и журнал рядом с печью',i:'<path d="M6 20h12M8 20v-5a4 4 0 0 1 8 0v5"/><path d="M12 3c3 3 4 5 2 8-1-2-3-3-2-8Z"/>'},
 {id:'steels',n:'Стали',t:'Марочник',s:'Режимы и аналоги',i:'<path d="M4 7h16M4 12h16M4 17h10"/>'},
 {id:'reg',n:'Расчёты',t:'Режимы',s:'Отпуск, цементация и карта',i:'<path d="M12 3v6m0 0-3-3m3 3 3-3"/><rect x="4" y="11" width="16" height="9" rx="2"/>'},
 {id:'learn',n:'Учёба',t:'Учёба',s:'От первого дня до технологии',i:'<path d="M4 6h16v12H4z"/><path d="M8 10h8M8 14h5"/>'},
 {id:'more',n:'Ещё',t:'О программе',s:'Источники, версия и данные',i:'<circle cx="12" cy="5" r="1.6"/><circle cx="12" cy="12" r="1.6"/><circle cx="12" cy="19" r="1.6"/>'}
);
[['tsafe','Безопасность термиста','Печь, огонь, масло, газы и блокировки'],['furnace','Печи и оснастка','Типы печей, садка и равномерность'],['pyro','Температура и пирометрия','Термопара, контрольная зона и погрешность'],['atmo','Атмосфера печи','Окисление, обезуглероживание и потенциал'],['quench','Закалочные среды','Вода, масло, полимер, газ и перемешивание'],['distort','Коробление и трещины','Как конструкция и цикл создают напряжения'],['metal','Контроль структуры','Шлиф, травление, твёрдость и образец-свидетель'],['docs','Документация садки','Прослеживаемость, отклонения и выпуск']].forEach(x=>{if(!FOLDERS.learn.some(y=>y[0]===x[0]))FOLDERS.learn.push(x);});

function tstate(){return{batches:[],checks:{},...tload(STORE,{})};}
function workHome(){const s=tstate(),last=s.batches[0];return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/therm-work-v99.jpg')"><span class="kicker">Рабочий центр · 0.99</span><h2>Садка под контролем</h2><p>Марка, цикл, выдержка, среда, фактическая твёрдость и отклонения собраны в одном офлайн-приложении.</p></div>${last?`<div class="card"><div class="flabel"><span>Последняя запись</span><span class="v99-source-badge">локальный журнал</span></div><div class="row" style="margin-top:8px"><b style="font:500 18px Oswald">${tx(last.steel)}</b><span class="hrcbox">${tx(last.actual||'без замера')}</span></div><div class="ct" style="font-size:11.5px;margin-top:5px">${tx(last.process)} · ${tx(last.temp)} °C · ${tx(last.ts)}</div></div>`:''}<div class="v99-grid">${WORK.map(x=>`<div class="v99-card ${x.bg}" data-twork="${x.id}"><i>${x.icon}</i><b>${x.n}</b><span>${x.d}</span></div>`).join('')}</div><div class="sec">Быстрый доступ</div><div class="v99-strip"><button class="v99-pill" data-troute="reg:temper">Подбор отпуска</button><button class="v99-pill" data-troute="reg:cement">Цементация</button><button class="v99-pill" data-troute="steels:">Найти сталь</button><button class="v99-pill" data-troute="learn:tsafe">Безопасность</button><button class="v99-pill" data-troute="learn:defect">Дефекты</button></div><div class="v99-source"><b>Политика точности:</b> приложение помогает проверить логику и не забыть контрольные точки. Конкретная температура, выдержка, допустимая садка и среда берутся из утверждённого техпроцесса, паспорта материала и инструкции печи.</div>${CREDIT}</div>`;}

function processDiagram(){return `<div class="v99-diagram"><svg viewBox="0 0 360 180" role="img" aria-label="Схема цикла термообработки"><g stroke="#303a42"><path d="M35 20v130h305"/><path d="M35 120h305M35 80h305M35 40h305" opacity=".45"/></g><path class="hot" stroke-width="4" d="M36 145 115 48h105l86 92"/><path class="cold" stroke-width="3" stroke-dasharray="6 5" d="M220 48 246 142"/><g><text x="45" y="164">время</text><text x="5" y="25">°C</text><text x="70" y="112">нагрев</text><text x="142" y="42">выдержка</text><text x="252" y="112">охлаждение</text></g><g fill="#ff8c28"><circle cx="115" cy="48" r="4"/><circle cx="220" cy="48" r="4"/></g></svg></div>`;}
function viewCycle(){return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/therm-process-v99.jpg')"><span class="kicker">Планирование</span><h2>Карта цикла</h2><p>Ориентировочная длительность нужна для планирования. Технологические времена не заменяются расчётом телефона.</p></div><div class="calc"><div class="tag">Оценка длительности</div><div class="two" style="margin-top:11px"><label class="fld"><span>Начальная T, °C</span><input type="number" id="cyStart" value="20"></label><label class="fld"><span>Целевая T, °C</span><input type="number" id="cyTarget" value="850"></label></div><div class="two"><label class="fld"><span>Скорость нагрева, °C/мин</span><input type="number" id="cyRate" value="8" step="0.5"></label><label class="fld"><span>Расчётное сечение, мм</span><input type="number" id="cySection" value="40"></label></div><label class="fld"><span>Коэффициент выдержки, мин/мм</span><select id="cyK"><option value="0.5">0,5 · условная оценка</option><option value="0.8" selected>0,8 · средняя оценка</option><option value="1">1,0 · консервативно</option><option value="1.5">1,5 · массивная садка</option></select></label><div class="out" id="cyOut">—</div><div class="hint">Коэффициент задаёт пользователь по своему техпроцессу. Реальная выдержка отсчитывается после выравнивания температуры садки, а не после команды нагрева.</div></div>${processDiagram()}<div id="cyBreak"></div><div class="v99-source"><b>Основа:</b> термообработка — управляемый цикл «нагрев → выравнивание → выдержка → охлаждение → контроль». Для отпуска температура всегда ниже критической A1; назначение отпуска — требуемое соотношение твёрдости и вязкости.</div></div>`;}

const HARD=[[15,202,210],[20,235,247],[25,266,279],[30,302,320],[35,336,358],[40,375,400],[45,421,450],[50,481,513],[55,560,595],[60,654,697],[65,739,832]];
function interp(points,x,xi,yi){if(x<=points[0][xi])return points[0][yi];if(x>=points[points.length-1][xi])return points[points.length-1][yi];for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1];if(x>=a[xi]&&x<=b[xi])return a[yi]+(x-a[xi])*(b[yi]-a[yi])/(b[xi]-a[xi]);}return NaN;}
function hardnessConvert(scale,value){const idx={HRC:0,HB:1,HV:2}[scale],v=+value;if(idx==null||!Number.isFinite(v))return null;return{HRC:interp(HARD,v,idx,0),HB:interp(HARD,v,idx,1),HV:interp(HARD,v,idx,2)};}
function viewHard(){return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/therm-steels-v99.jpg')"><span class="kicker">Контроль твёрдости</span><h2>HRC · HB · HV</h2><p>Перевод используется для ориентирования и выбора метода. Приёмка выполняется измерением в требуемой шкале.</p></div><div class="calc"><div class="two"><label class="fld"><span>Исходная шкала</span><select id="hcScale"><option>HRC</option><option>HB</option><option>HV</option></select></label><label class="fld"><span>Значение</span><input type="number" id="hcValue" value="40" step="1"></label></div><div class="v99-kpis"><div class="v99-kpi"><span>Rockwell C</span><b id="hcHRC">—</b></div><div class="v99-kpi"><span>Brinell</span><b id="hcHB">—</b></div><div class="v99-kpi"><span>Vickers</span><b id="hcHV">—</b></div><div class="v99-kpi"><span>Диапазон</span><b style="font-size:14px" id="hcBand">—</b></div></div></div><div class="card"><div class="tag">Когда какую шкалу</div><div class="ct" style="margin-top:8px"><b>HRC</b> — закалённые стали и твёрдые детали; <b>HB</b> — более мягкие и неоднородные материалы с крупным отпечатком; <b>HV</b> — широкий диапазон, тонкие слои и микротвёрдость при подходящей нагрузке и подготовке поверхности.</div></div><div class="v99-source"><b>Нормативная основа:</b> ISO 6508 — Rockwell, ISO 6506 — Brinell, ISO 6507 — Vickers, ISO 18265 — перевод значений. Пересчёт приблизительный и зависит от материала; он не заменяет испытание.</div></div>`;}

function viewTimer(){return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/therm-process-v99.jpg')"><span class="kicker">Рядом с печью</span><h2>Таймер выдержки</h2><p>Работает локально. Не является контуром управления печью и не заменяет штатную автоматику.</p></div><div class="card"><div class="two"><label class="fld"><span>Минуты</span><input type="number" id="tmMin" value="30" min="0"></label><label class="fld"><span>Секунды</span><input type="number" id="tmSec" value="0" min="0" max="59"></label></div><div class="v99-timer" id="tmOut">30:00</div><div class="v99-actions three"><button class="v99-mini primary" id="tmStart">Старт</button><button class="v99-mini" id="tmPause">Пауза</button><button class="v99-mini" id="tmReset">Сброс</button></div></div><div class="v99-status warn"><b>Отсчёт начинайте по карте процесса.</b><span>Для многих циклов выдержка начинается после прогрева и выравнивания температуры садки, а не сразу после закрытия двери.</span></div></div>`;}

function viewBatch(){const s=tstate();return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/therm-work-v99.jpg')"><span class="kicker">Прослеживаемость</span><h2>Журнал садок</h2><p>Короткая запись фактического режима и результата. Данные остаются на устройстве.</p></div><div class="card"><div class="two"><label class="fld"><span>Марка стали</span><input id="btSteel" value="40Х"></label><label class="fld"><span>Садка / партия</span><input id="btNo" placeholder="26-0830-1"></label></div><label class="fld"><span>Процесс</span><select id="btProcess"><option>Закалка + отпуск</option><option>Нормализация</option><option>Отжиг</option><option>Цементация</option><option>Отпуск</option><option>Другое</option></select></label><div class="two"><label class="fld"><span>Температура, °C</span><input type="number" id="btTemp" value="850"></label><label class="fld"><span>Выдержка, мин</span><input type="number" id="btHold" value="60"></label></div><div class="two"><label class="fld"><span>Среда</span><input id="btMedium" value="Масло"></label><label class="fld"><span>Факт твёрдости</span><input id="btActual" placeholder="HRC 30"></label></div><label class="fld"><span>Отклонение / наблюдение</span><textarea id="btNote" placeholder="Температура масла, задержка переноса, коробление…"></textarea></label><button class="btn" id="btSave">Сохранить садку</button></div><div class="card"><div class="row"><div class="tag">История</div><button class="v99-mini" id="btExport">Экспорт JSON</button></div><div id="btList" style="margin-top:8px">${batchList(s.batches)}</div></div></div>`;}
function batchList(a){return(a||[]).slice(0,30).map((x,i)=>`<div style="padding:9px 0;border-bottom:1px solid #24272c"><div class="row"><b style="font:500 15px Oswald">${tx(x.steel)} · ${tx(x.no||'без №')}</b><span class="hrcbox">${tx(x.actual||'—')}</span></div><div class="ct" style="font-size:11px;margin-top:4px">${tx(x.process)} · ${tx(x.temp)} °C / ${tx(x.hold)} мин · ${tx(x.medium)}</div>${x.note?`<div class="hint">${tx(x.note)}</div>`:''}</div>`).join('')||'<div class="hint">Записей пока нет.</div>';}

const DEF={soft:['Недостаточная твёрдость',['Сверить фактическую температуру детали и выдержку','Проверить задержку переноса и температуру среды','Исключить обезуглероженный слой: сравнить поверхность и подслой','Проверить марку стали и прокаливаемость сечения']],spots:['Мягкие пятна',['Осмотреть окалину и загрязнение','Проверить перемешивание и паровую рубашку','Сравнить положение деталей в садке','Проверить поверхность несколькими отпечатками']],crack:['Трещины',['Остановить выпуск партии и зафиксировать место трещин','Проверить перегрев, острые переходы и задержку отпуска','Проверить жёсткость и температуру закалочной среды','Назначить НК по техпроцессу']],warp:['Коробление',['Сравнить ориентацию и опоры деталей в садке','Проверить равномерность нагрева и перемешивания среды','Проверить остаточные напряжения после мехобработки','Измерить до и после каждого этапа на пробной детали']],decarb:['Обезуглероживание',['Проверить атмосферу, герметичность и время нагрева','Сделать профиль микротвёрдости от поверхности','Проверить припуск и защитное покрытие','Не принимать решение по одному поверхностному HRC'] ]};
function diagnose(k){return DEF[k]||DEF.soft;}
function viewDefect(){return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/therm-steels-v99.jpg')"><span class="kicker">Не угадывать — проверять</span><h2>Диагностика брака</h2><p>Помощник строит порядок проверки, но не назначает повторную термообработку автоматически.</p></div><div class="card"><label class="fld"><span>Главный признак</span><select id="dfKind"><option value="soft">Недостаточная твёрдость</option><option value="spots">Мягкие пятна</option><option value="crack">Трещины</option><option value="warp">Коробление</option><option value="decarb">Обезуглероживание</option></select></label><label class="fld"><span>Контекст</span><textarea id="dfContext" placeholder="Марка, сечение, цикл, место дефекта…"></textarea></label><button class="btn" id="dfRun">Построить проверку</button></div><div id="dfOut"></div></div>`;}

const CHECKS=[['id','Материал и партия','Марка, плавка и количество совпадают с картой'],['recipe','Рецепт и печь','Номер программы, зона и уставки проверены'],['load','Садка и оснастка','Детали не экранируют друг друга, оснастка исправна'],['sensor','Контроль температуры','Термопара, регистратор и срок поверки проверены'],['medium','Среда охлаждения','Уровень, температура, перемешивание и пожарная защита готовы'],['ppe','СИЗ и зона','Щиток, перчатки, одежда, проход и аварийный выход свободны'],['trace','Образец и журнал','Свидетель, номер садки и план замеров подготовлены']];
function viewFurnace(){const s=tstate();return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/therm-work-v99.jpg')"><span class="kicker">Перед запуском цикла</span><h2>Печь и садка готовы?</h2><p>Короткая защита от пропуска очевидного. Штатная инструкция предприятия имеет приоритет.</p></div><div class="card">${CHECKS.map(x=>`<label class="v99-check"><input type="checkbox" data-tcheck="${x[0]}" ${s.checks[x[0]]?'checked':''}><span><b>${x[1]}</b><span>${x[2]}</span></span></label>`).join('')}<div class="v99-progress-row"><b>Готовность</b><span id="fcPct">0%</span></div><div class="v99-progress"><i id="fcBar" style="width:0"></i></div></div><div class="v99-status bad"><b>Не обходить блокировки и не работать внутри печи без LOTO.</b><span>Опасности включают выброс пламени, зажатие дверью, горячее масло, пожар и недостаток кислорода. Обслуживание выполняется по наряду и процедуре предприятия.</span></div></div>`;}

function academy(){const p=tload(LEARN,{}),done=FOLDERS.learn.filter(x=>p[x[0]]).length,total=FOLDERS.learn.length,pc=Math.round(done/total*100);return `<div class="wrap"><div class="v99-hero" style="--v99-bg:url('./assets/backgrounds/therm-learn-v99.jpg')"><span class="kicker">Академия термиста</span><h2>От безопасной садки до анализа структуры</h2><p>Учимся видеть процесс целиком: материал, печь, температура, среда, структура, твёрдость и документирование.</p></div><div class="card"><div class="v99-progress-row"><b>Пройдено тем</b><span>${done}/${total} · ${pc}%</span></div><div class="v99-progress"><i style="width:${pc}%"></i></div></div><div class="v99-grid"><div class="v99-card tl" data-troute="learn:tsafe"><i>1</i><b>Первый день</b><span>Опасности печи и закалочной среды</span></div><div class="v99-card tp" data-troute="learn:pyro"><i>2</i><b>Температура</b><span>Термопара, зона и регистрация</span></div><div class="v99-card ts" data-troute="learn:hard"><i>3</i><b>Твёрдость</b><span>Метод, поверхность и шкала</span></div><div class="v99-card tw" data-troute="learn:docs"><i>4</i><b>Садка</b><span>Запись, отклонение и выпуск</span></div></div><div class="v99-source"><b>Проверяемая основа:</b> ISO 6506/6507/6508 для испытаний твёрдости; ISO 18265 для ориентировочного перевода; утверждённый техпроцесс и инструкция печи для конкретного режима.</div></div>`;}

function extraLearn(f){const src='<div class="v99-source"><b>Важно:</b> это учебный порядок проверки. Численные режимы назначаются технологической документацией предприятия и подтверждаются контрольным образцом.</div>';
 if(f==='tsafe')return `<div class="wrap"><div class="card"><div class="tag">Главные риски</div><div class="ct" style="margin-top:8px">Ожог излучением и пламенем, выброс горячего масла, пожар, защемление дверью или механизмом загрузки, токсичная или бескислородная атмосфера, падение горячей садки. Любая неисправная блокировка означает остановку и вызов ответственного.</div></div><div class="card"><div class="tag">Перед открытием</div><ol class="seq"><li>Сверить состояние цикла и давление/атмосферу.</li><li>Убедиться, что зона выгрузки свободна и закалочный бак готов.</li><li>Проверить СИЗ, захват и путь переноса.</li><li>Открывать из безопасной позиции по инструкции печи.</li><li>Не работать одному там, где регламент требует наблюдающего.</li></ol></div>${src}</div>`;
 if(f==='furnace')return `<div class="wrap"><div class="card"><div class="tag">Что определяет результат</div><div class="ct" style="margin-top:8px">Не только уставка контроллера: загрузка зоны, масса оснастки, расстояние между деталями, циркуляция, состояние нагревателей, положение рабочей термопары и фактическая температура металла.</div></div>${processDiagram()}<div class="card"><div class="tag">Практическая проверка</div><div class="ct" style="margin-top:8px">Сравнивайте одинаковые позиции садки, фиксируйте время выхода на режим, используйте образец-свидетель и не переносите режим между печами без подтверждения.</div></div>${src}</div>`;
 if(f==='pyro')return `<div class="wrap"><div class="card"><div class="tag">Цепочка измерения</div><div class="v99-diagram"><svg viewBox="0 0 360 116"><g fill="#151b20" stroke="#3b4650"><rect x="10" y="35" width="72" height="38" rx="7"/><rect x="105" y="35" width="72" height="38" rx="7"/><rect x="200" y="35" width="72" height="38" rx="7"/><rect x="295" y="35" width="55" height="38" rx="7"/></g><g text-anchor="middle"><text x="46" y="58">ТЕРМОПАРА</text><text x="141" y="58">КАБЕЛЬ</text><text x="236" y="58">РЕГУЛЯТОР</text><text x="322" y="58">ЗАПИСЬ</text></g><g class="hot" stroke-width="2"><path d="M82 54h23M177 54h23M272 54h23"/></g></svg></div><div class="ct">Ошибка возможна на каждом звене: тип термопары, компенсационный провод, полярность, контакт, дрейф датчика, настройка прибора и положение в рабочей зоне.</div></div>${src}</div>`;
 if(f==='atmo')return `<div class="wrap"><div class="card"><div class="tag">Три вопроса к атмосфере</div><div class="ct" style="margin-top:8px"><b>Что защищаем?</b> поверхность от окисления и обезуглероживания. <b>Что контролируем?</b> состав/потенциал, расход, давление, герметичность и точку росы — если это предусмотрено системой. <b>Что проверяем?</b> поверхность, микроструктуру и профиль твёрдости.</div></div><div class="note warn"><b>Газовая атмосфера может быть горючей или токсичной.</b> Не ищите утечку открытым огнём и не входите в замкнутое пространство без процедуры предприятия.</div>${src}</div>`;
 if(f==='quench')return `<div class="wrap"><div class="card"><div class="tag">Среда — часть процесса</div><div class="tscroll" style="margin-top:8px"><table><thead><tr><th>Среда</th><th>Особенность</th><th>Контроль</th></tr></thead><tbody><tr><td>Вода</td><td>Высокая интенсивность, риск трещин и паровой рубашки</td><td>температура, движение, загрязнение</td></tr><tr><td>Масло</td><td>Мягче воды, пожароопасно</td><td>температура, вязкость, уровень, вспышка</td></tr><tr><td>Полимер</td><td>Интенсивность зависит от концентрации</td><td>концентрация, температура, перемешивание</td></tr><tr><td>Газ</td><td>Чисто и управляемо, зависит от давления/потока</td><td>давление, расход, загрузка</td></tr></tbody></table></div></div>${src}</div>`;
 if(f==='distort')return `<div class="wrap"><div class="card"><div class="tag">Почему ведёт деталь</div><div class="ct" style="margin-top:8px">Температурные градиенты и структурное превращение меняют объём не одновременно по всему сечению. Геометрические концентраторы, неодинаковая толщина, остаточные напряжения после резания и несимметричная опора усиливают результат.</div></div><div class="card"><div class="tag">План эксперимента</div><ol class="seq"><li>Измерить деталь до обработки.</li><li>Зафиксировать ориентацию в садке.</li><li>Не менять одновременно несколько параметров.</li><li>Измерить после закалки и после отпуска отдельно.</li><li>Сравнить минимум три одинаковые детали.</li></ol></div>${src}</div>`;
 if(f==='metal')return `<div class="wrap"><div class="card"><div class="tag">Контроль от простого к сложному</div><ol class="seq"><li>Внешний вид и отсутствие явных трещин.</li><li>Твёрдость в заданной шкале на подготовленной поверхности.</li><li>Профиль твёрдости или микротвёрдость для слоя.</li><li>Макрошлиф/микрошлиф при споре о структуре или глубине слоя.</li><li>Неразрушающий контроль по техпроцессу.</li></ol></div><div class="note">Один отпечаток не описывает неоднородную деталь. Количество и расположение точек задаёт методика контроля.</div>${src}</div>`;
 return `<div class="wrap"><div class="card"><div class="tag">Минимальная запись садки</div><div class="ct" style="margin-top:8px">Марка и партия, деталь и количество, печь и программа, время начала/окончания, фактическая температурная запись, среда охлаждения, задержки и отклонения, образец-свидетель, точки и результат измерения, решение ответственного.</div></div><div class="card"><div class="tag">Отклонение</div><div class="ct" style="margin-top:8px">Не исправляйте журнал задним числом. Зафиксируйте факт, изолируйте партию, приложите запись печи и результаты контроля, затем передайте решение уполномоченному технологу.</div></div>${src}</div>`;
}

const rawSteels=viewSteels;viewSteels=function(){return `<div class="wrap"><div class="v99-source"><b>Уровень данных: справочный.</b> Марка и диапазон помогают найти отправную точку; выпуск партии выполняется только по утверждённому техпроцессу, сертификату материала и фактическому контролю.</div></div>`+rawSteels();};
const rawCement=viewCement;viewCement=function(){return `<div class="wrap"><div class="v99-source"><b>Расчёт слоя — оценка диффузии.</b> Эффективную глубину подтверждают на образце-свидетеле по принятой на предприятии методике.</div></div>`+rawCement();};
const rawTemper=viewTemper;viewTemper=function(){return `<div class="wrap"><div class="v99-source"><b>Кривая отпуска ориентировочная.</b> Она помогает выбрать область поиска, но температура выпуска определяется фактической твёрдостью и технологической документацией.</div></div>`+rawTemper();};
const rawMore=viewMore;viewMore=function(){return `<div class="wrap"><div class="card"><div class="tag">Проверяемые источники 0.99</div><div class="v99-source"><a href="https://www.iso.org/committee/53558/x/catalogue/" target="_blank" rel="noopener">ISO/TC 164/SC 3</a> — стандарты испытаний твёрдости ISO 6506, 6507 и 6508.</div><div class="v99-source"><a href="https://www.bodycote.com/what-we-do/precision-heat-treatment/hardening-and-tempering-atmosphere-vacuum/tempering/" target="_blank" rel="noopener">Bodycote: tempering</a> — назначение отпуска и связь твёрдости с вязкостью.</div><div class="v99-source"><a href="https://www.bodycote.com/what-we-do/precision-heat-treatment/case-hardening-atmosphere-vacuum/atmospheric-carburising/" target="_blank" rel="noopener">Bodycote: carburising</a> — принцип цементации, закалка и последующий отпуск.</div><div class="v99-source"><a href="https://www.osha.gov/control-hazardous-energy" target="_blank" rel="noopener">OSHA: hazardous energy</a> — изоляция энергии при обслуживании оборудования.</div></div></div>`+rawMore();};

const baseLearn=learnContent;learnContent=function(f){let h=['tsafe','furnace','pyro','atmo','quench','distort','metal','docs'].includes(f)?extraLearn(f):baseLearn(f),p=tload(LEARN,{});return h+`<div class="wrap"><div class="card"><label class="v99-check" style="margin:0"><input type="checkbox" data-tlearn="${tx(f)}" ${p[f]?'checked':''}><span><b>Тема изучена и обсуждена с наставником</b><span>Отметка не заменяет проверку практического навыка и допуск.</span></span></label></div></div>`;};

function custom(title,sub,html,section){$('#ttl').textContent=title;$('#sub').textContent=sub;$('#searchbox').style.display='none';$('#chips').style.display='none';$('#fab').style.display='none';drawNav();$('#screen').innerHTML=html;if(dev)dev.dataset.section=section;bind();numFix();$('#screen').classList.remove('v99-enter');void $('#screen').offsetWidth;$('#screen').classList.add('v99-enter');$('#screen').scrollTop=0;}
const baseRender=render;render=function(){if(tab==='work'){if(!folder)return custom('Работа термиста','Цикл, контроль и журнал',workHome(),'work');const v={cyclex:['Карта цикла','Оценка времени и контрольные точки',viewCycle(),'reg'],hardx:['Перевод твёрдости','HRC, HB и HV',viewHard(),'steels'],timerx:['Таймер выдержки','Локальный вспомогательный таймер',viewTimer(),'reg'],batchx:['Журнал садок','Фактические режимы и результат',viewBatch(),'work'],defx:['Диагностика брака','Порядок проверки причин',viewDefect(),'steels'],furnacex:['Перед запуском','Проверка печи, садки и среды',viewFurnace(),'work']}[folder];if(v)return custom(...v);}if(tab==='learn'&&!folder)return custom('Академия термиста','С нуля до контроля процесса',academy()+`<div class="wrap">${FOLDERS.learn.map(x=>`<div class="card" data-folder="${x[0]}"><div class="glow"></div><div style="font:500 17px Oswald">${x[1]}</div><div class="ct" style="font-size:12px;margin-top:3px">${x[2]}</div></div>`).join('')}${CREDIT}</div>`,'learn');baseRender();if(dev)dev.dataset.section=tab;$('#screen').classList.remove('v99-enter');void $('#screen').offsetWidth;$('#screen').classList.add('v99-enter');};

const baseBind=bind;bind=function(){baseBind();bind99();};
function bind99(){document.querySelectorAll('[data-twork]').forEach(x=>x.onclick=()=>{tab='work';folder=x.dataset.twork;deeper();render();});document.querySelectorAll('[data-troute]').forEach(x=>x.onclick=()=>{const [t,f]=x.dataset.troute.split(':');tab=t;folder=f||null;rank=null;filter='Все';deeper();render();});document.querySelectorAll('[data-tlearn]').forEach(x=>x.onchange=()=>{const p=tload(LEARN,{});p[x.dataset.tlearn]=x.checked;tsave(LEARN,p);toast(x.checked?'Тема отмечена':'Отметка снята');});bindCycle();bindHard();bindTimer();bindBatch();bindDefect();bindFurnace();}
function bindCycle(){const out=$('#cyOut');if(!out)return;const calc=()=>{const a=+$('#cyStart').value,b=+$('#cyTarget').value,r=+$('#cyRate').value,s=+$('#cySection').value,k=+$('#cyK').value;if(!(b>a&&r>0&&s>0)){out.innerHTML='—';return;}const heat=(b-a)/r,hold=s*k,total=heat+hold;out.innerHTML=`${Math.round(total)}<small>мин · нагрев ${Math.round(heat)} + выдержка ${Math.round(hold)}</small>`;$('#cyBreak').innerHTML=`<div class="v99-kpis"><div class="v99-kpi"><span>Нагрев</span><b>${Math.round(heat)} мин</b></div><div class="v99-kpi"><span>Выдержка</span><b>${Math.round(hold)} мин</b></div></div>`;};['cyStart','cyTarget','cyRate','cySection','cyK'].forEach(id=>$('#'+id).oninput=calc);calc();}
function bindHard(){if(!$('#hcValue'))return;const calc=()=>{const r=hardnessConvert($('#hcScale').value,+$('#hcValue').value);if(!r)return;$('#hcHRC').textContent=r.HRC.toFixed(1);$('#hcHB').textContent=Math.round(r.HB);$('#hcHV').textContent=Math.round(r.HV);$('#hcBand').textContent=r.HRC<20?'мягче диапазона':r.HRC<40?'средняя':'закалённая';};$('#hcScale').onchange=calc;$('#hcValue').oninput=calc;calc();}
function fmtTime(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function paintTimer(){const o=$('#tmOut');if(o){o.textContent=fmtTime(Math.max(0,timerLeft));o.classList.toggle('run',timerRunning);}}
function bindTimer(){if(!$('#tmOut'))return;if(!timerLeft)timerLeft=(+$('#tmMin').value||0)*60+(+$('#tmSec').value||0);paintTimer();$('#tmStart').onclick=()=>{if(!timerLeft)timerLeft=(+$('#tmMin').value||0)*60+(+$('#tmSec').value||0);timerRunning=true;clearInterval(timerId);timerId=setInterval(()=>{timerLeft--;paintTimer();if(timerLeft<=0){clearInterval(timerId);timerRunning=false;paintTimer();toast('Выдержка завершена');try{navigator.vibrate&&navigator.vibrate([300,150,300]);}catch(_){}}},1000);paintTimer();};$('#tmPause').onclick=()=>{timerRunning=false;clearInterval(timerId);paintTimer();};$('#tmReset').onclick=()=>{timerRunning=false;clearInterval(timerId);timerLeft=(+$('#tmMin').value||0)*60+(+$('#tmSec').value||0);paintTimer();};}
function bindBatch(){if(!$('#btSave'))return;$('#btSave').onclick=()=>{const s=tstate(),x={steel:$('#btSteel').value.trim(),no:$('#btNo').value.trim(),process:$('#btProcess').value,temp:+$('#btTemp').value,hold:+$('#btHold').value,medium:$('#btMedium').value.trim(),actual:$('#btActual').value.trim(),note:$('#btNote').value.trim(),ts:new Date().toLocaleString('ru-RU')};if(!x.steel||!x.temp){toast('Укажите сталь и температуру');return;}s.batches.unshift(x);s.batches=s.batches.slice(0,100);tsave(STORE,s);render();};$('#btExport').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(tstate().batches,null,2)],{type:'application/json'}));a.download='razryad-termist-sadki.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);};}
function bindDefect(){if(!$('#dfRun'))return;$('#dfRun').onclick=()=>{const r=diagnose($('#dfKind').value),ctx=$('#dfContext').value.trim();$('#dfOut').innerHTML=`<div class="card"><div class="tag">${r[0]}</div>${ctx?`<div class="ct" style="margin-top:7px">Контекст: ${tx(ctx)}</div>`:''}<div class="sec">Проверить по порядку</div><ol class="seq">${r[1].map(x=>`<li>${x}</li>`).join('')}</ol><div class="note warn"><b>До решения технолога:</b> партию изолировать, не смешивать с годной и не назначать повторный нагрев автоматически.</div></div>`;};}
function bindFurnace(){const a=[...document.querySelectorAll('[data-tcheck]')];if(!a.length)return;const upd=()=>{const s=tstate();a.forEach(x=>s.checks[x.dataset.tcheck]=x.checked);tsave(STORE,s);const pc=Math.round(a.filter(x=>x.checked).length/a.length*100);$('#fcPct').textContent=pc+'%';$('#fcBar').style.width=pc+'%';};a.forEach(x=>x.onchange=upd);upd();}

function installSearch(){const brand=document.querySelector('header .brand');if(!brand||$('#tSearchBtn'))return;brand.insertAdjacentHTML('beforeend','<button class="v99-search-button" id="tSearchBtn" aria-label="Поиск по приложению"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg></button>');dev.insertAdjacentHTML('beforeend','<div class="v99-search-overlay" id="tSearch"><div class="v99-search-head"><div class="v99-search-row"><input id="tSearchQ" placeholder="Сталь, расчёт, процесс, тема…"><button class="v99-search-button" id="tSearchClose">×</button></div><div class="hint">Ищет по марочнику, режимам, инструментам и учебнику</div></div><div class="v99-search-results" id="tSearchResults"></div></div>');$('#tSearchBtn').onclick=()=>{$('#tSearch').classList.add('open');$('#tSearchQ').value='';drawSearch();setTimeout(()=>$('#tSearchQ').focus(),20);};$('#tSearchClose').onclick=()=>$('#tSearch').classList.remove('open');$('#tSearchQ').oninput=drawSearch;}
function searchItems(){const a=[];WORK.forEach(x=>a.push({k:'work',id:x.id,n:x.n,d:x.d,i:x.icon}));Object.entries(FOLDERS).forEach(([tab0,list])=>list.forEach(x=>a.push({k:'route',tab:tab0,id:x[0],n:x[1],d:x[2],i:tab0==='learn'?'A':'°'})));if(DB&&DB.steels)DB.steels.forEach(x=>a.push({k:'steel',id:x.id,n:x.grade,d:x.group+' '+x.analogs,i:'Fe'}));return a;}
function drawSearch(){const q=($('#tSearchQ').value||'').trim().toLowerCase(),w=q.split(/\s+/).filter(Boolean),list=searchItems().filter(x=>!w.length||w.every(z=>(x.n+' '+x.d).toLowerCase().includes(z))).slice(0,60);$('#tSearchResults').innerHTML=list.map((x,i)=>`<div class="v99-search-item" data-tsi="${i}"><i>${tx(x.i)}</i><div><b>${tx(x.n)}</b><span>${tx(x.d)}</span></div></div>`).join('')||'<div class="empty">Ничего не найдено.</div>';document.querySelectorAll('[data-tsi]').forEach(el=>el.onclick=()=>openSearch(list[+el.dataset.tsi]));}
function openSearch(x){$('#tSearch').classList.remove('open');if(x.k==='steel'){tab='steels';folder=null;render();setTimeout(()=>openSheet(x.id),0);return;}if(x.k==='work'){tab='work';folder=x.id;}else{tab=x.tab;folder=x.id;}deeper();render();}
installSearch();

window.RazryadThermistV99={hardnessConvert,diagnose,processEstimate:(start,target,rate,section,k)=>({heat:(target-start)/rate,hold:section*k,total:(target-start)/rate+section*k}),searchItems};
tab='work';folder=null;render();
})();
